[metadata]
description = Diabetes Prediction App
long_description = file: README.md
long_description_content_type = text/markdown

[options]
package_dir = 
    = .
packages = find:
python_requires = >=3.10,<3.11

[options.packages.find]
where = .
include = *

egg_info
tags
.git
.gitignore
.github
.mypy_cache
.pytest_cache
__pycache__
venv
*.pyc
*.pyo
*.pyd
.Python
*.so
.env
*.csv
*.joblib
.DS_Store
.idea/
.vscode/
*.log
*.swp
*.egg-info/
build/
dist/
